version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    depends_on:
      - postgres
    volumes:
      - ./backend:/app

  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: game-review-portal
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  backend:
  pg_data:
